### ISSUE TITLE
Support custom timezone in the template rather than default UTC

### ISSUE THREAD

**Issue by fbchan** [F5Networks/f5-openstack-hot#11]
In the onboard.sh script, it hardcoded "-tz UTC". Ideal if can be parametrised to take timezone options.

**Comment by fbchan** [comment]
#

**Comment by kaustriaf5** [comment]
Fixed in this release:
https://github.com/F5Networks/f5-openstack-hot/releases/tag/v4.0.0

@fbchan
You can now pass this param:
`bigip_timezone`
e.g. in the env file:
`bigip_timezone: GMT`
Default is `UTC`
