### ISSUE TITLE
Allow connection to SSL (HEAT API Service) without cert verification check

### ISSUE THREAD

**Issue by fbchan** [F5Networks/f5-openstack-hot#12]
As part of the on-boarding process (onboard.sh, onboard-network.sh, onboard-cluster.sh preOnboard.sh and postOnboard.sh) a function send_heat_signal was used to signal back to HEAT API services related it status. A runtime generated command similar to below will be generated.

curl -i -X POST -H 'X-Auth-Token: e760119688cb4a4111e0bce25d420ef2' -H 'Content-Type: application/json' -H xxxxxxxx

An error will be thrown on onboard logs similar to below and HEAT API will not receive notification on on-boarding status.
-----------------------------------
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
 
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
-----------------------------------

Recommend to include "-k" in the curl command to ensure if environment build with TLS/SSL (which common in a production environment) to ignore/off curl certificate verification check. "-k" will works with or without TLS/SSL environment. Hence, probably can embedded as part of the runtime generated command.

My temporary workaround is to add "-k" for all those script and tested consistently working in my environment, where the send_heat_signal able to notify HEAT API service on it status.
Example
=======
onboard.sh:    wc_notify -k --data-binary xxxxxxxxx

**Comment by kaustriaf5** [comment]
Fixed in this release:
https://github.com/F5Networks/f5-openstack-hot/releases/tag/v4.0.0

@fbchan 
You can now pass this param:
`os_heat_wc_notify_options`
e.g. in the env file:
`os_heat_wc_notify_options: -k -v`
