### ISSUE TITLE
nnic not working. 

### ISSUE THREAD

**Issue by firefly2000** [F5Networks/f5-openstack-hot#13]
use 13.1.0.1 image (unzip) and updated environmental file and loaded locally to openstack controller. 

openstack stack create test -t https://raw.githubusercontent.com/F5Networks/f5-openstack-hot/master/supported/templates/standalone/nnic/f5_bigip_standalone_n_nic.yaml -e bigip-13-1-2nic-env.yaml 

**Could not fetch contents for file:///../networks/bigip_nnic_handler.yaml**

**Comment by fbchan** [comment]
I believe if you clone the repo down and runs it, it will works. Its trying to reference those resource registry, handler, scripts and etc using unix notation ../../.

resource_registry:
  F5::BigIP::OverrideDefaultConfig: ../../../configs/override_default_config.yaml
  F5::BigIP::OnboardingLibs: ../../../configs/onboarding_libs.yaml
  F5::BigIP::OnboardingScripts: ../../../configs/onboarding_scripts.yaml

I clone it and runs it from my controller box. It works perfectly.

**Comment by kaustriaf5** [comment]
@firefly2000 , please see response from @fbchan - the paths in the environment files are relative.. So whatever you have specified in the resource_registry in bigip-13-1-2nic-env.yaml should point to to valid files. I noticed that you are referencing the template straight from github - if you don't download the set of templates and other resources locally you'd have to make sure to update the resource_registry items to point to their respective URLs.

**Comment by firefly2000** [comment]
Thank you! I uploaded f5-openstack-hot-supported.tar.gz to my controller and and works now for Mitaka. 

Pike is not working (ERROR: The Resource Type (F5::BigIP::NNicHandler) could not be found.), so two additional questions: 
- For supported templates, do I need to install F5 heat plugin? I do have plugin installed in Mitaka, but not Pike yet. 
- Are the templates supported in other newer version, such as Newton or Pike? If not yet, any plan? 

Thanks!

**Comment by kaustriaf5** [comment]
@firefly2000 , there are no F5 heat plugins required if you are using templates from this repo. 
The templates are not "officially" supported yet for newer versions so you'd have to try them out at this time.. They should work unless specific Heat resource types that are in the templates become deprecated or some component work differently in newer Heat versions. We don't have specific timeframe right now (latest feedback is that most are still on older versions). 
That error you are getting for Pike - are you using the exact same environment file, same templates and file locations? Does it actually create a stack and error out, or does validation fail and stack is not created? What does `openstack stack resource list <stack_name> show`?

**Comment by firefly2000** [comment]
yes, exact environment, did not create stack, just stuck with the error

**Comment by kaustriaf5** [comment]
Thanks @firefly2000 - please let me know if you find something further. 
I took a look [at this Pike doc ](https://docs.openstack.org/heat/pike/template_guide/composition.html#define-a-new-resource-type ) and it seems to be the same resource type definition to me. From the error you indicated above, I suspect somehow it is not resolving the path correctly for the nnic_handler template. 
Some additional troubleshooting that might help:
- In your _env.yaml file, try replacing the `resource_registry` entry to : 
`F5::BigIP::NNicHandler: file:///<full file path to repo root folder>/experimental/networks/bigip_nnic_handler.yaml` 
or
`F5::BigIP::NNicHandler: https://raw.githubusercontent.com/F5Networks/f5-openstack-hot/master/supported/networks/bigip_nnic_handler.yaml`
