### ISSUE TITLE
support more than 9 TMM interfaces

### ISSUE THREAD

**Issue by firefly2000** [F5Networks/f5-openstack-hot#15]
With 13.1.0, we are supporting up to 28 interfaces total. I see we have restriction on nnic to limit to 10 interfaces total. Could that be updated to allow 28 interfaces? 

Thank you!

**Comment by jgruber** [comment]
According to support:

https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ve-setup-linux-kvm-13-1-0.pdf

10 NICs max for KVM virtIO environment for 13.1. 

We'll consider changing our doc when the VE doc explicitly calls out > 10 NIC support. I do not believe anyone is testing this, so increasing the number of PCI devices addressed by VE would be venturing into new territory we do not support.

The newly refactored experimental HOT is n - NIC so we could easily support more when VE does.

**Comment by firefly2000** [comment]
Thanks! I only tested with 11 interfaces and works. I will go back to PM to confirm official supportability and update doc if supported.
