### ISSUE TITLE
Active standby support requested

### ISSUE THREAD

**Issue by vishwanathj** [F5Networks/f5-openstack-hot#19]
I see that only Active Active support is available as per link f5-openstack-hot/experimental/templates/cluster/nnic/existing_stack/static/, requesting that Active Standby support be added as well.

**Comment by vishwanathj** [comment]
Looks like the cluster template at f5-openstack-hot/experimental/templates/cluster/nnic/prod_stack/static/ provides the active standby configuration. This issue can be marked resolved.

**Comment by kaustriaf5** [comment]
Closing as per comment above.
