### ISSUE TITLE
"init_0_static_mgmt_config_bigip1" should be "init_0_static_mgmt_config_bigip2"  at L694 of f5_bigip_cluster_n_nic.yaml

### ISSUE THREAD

**Issue by vishwanathj** [F5Networks/f5-openstack-hot#20]
The second Big IP instance will fail to get a management IP address assigned due to the above mentioned typo at **L694** https://github.com/F5Networks/f5-openstack-hot/blob/master/experimental/templates/cluster/nnic/prod_stack/static/f5_bigip_cluster_n_nic.yaml

**Comment by kaustriaf5** [comment]
Thanks for reporting, will get this fixed.

**Comment by kaustriaf5** [comment]
@vishwanathj this is fixed in https://github.com/F5Networks/f5-openstack-hot/tree/v4.0.1
