### ISSUE TITLE
Heat template instantiation fails when subnet names are provided for "network_vlan_subnets" and requires subnet UUIDs instead.

### ISSUE THREAD

**Issue by vishwanathj** [F5Networks/f5-openstack-hot#22]
When attempting to instantiate the https://github.com/F5Networks/f5-openstack-hot/blob/master/experimental/templates/cluster/nnic/prod_stack/static/f5_bigip_cluster_n_nic.yaml template with the  f5-openstack-hot/experimental/templates/cluster/nnic/prod_stack/static/f5_bigip_cluster_n_nic_env.yaml updated to provide subnet names for the "**network_vlan_subnets**" I see the below error, I had to provide the Subnet UUIDs to go past the error.

2018-06-24 20:56:02Z [activeactive.bigip_nnic_handler_bigip1]: CREATE_FAILED  BadRequest: resources.bigip_nnic_handler_bigip1.resources.network_vlan_ports.resources.network_vlan_ports.resources[2].resources.bigip_neutron_port: Invalid input for fixed_ips. Reason: 'f5-ha-internal' is not a valid UUID.
Neutron server returns request_
2018-06-24 20:56:02Z [activeactive]: CREATE_FAILED  Resource CREATE failed: BadRequest: resources.bigip_nnic_handler_bigip1.resources.network_vlan_ports.resources.network_vlan_ports.resources[2].resources.bigip_neutron_port: Invalid input for fixed_ips. Reason: 'f5-ha-internal' is not a valid UUID.
Neutron
2018-06-24 20:56:04Z [activeactive.bigip_nnic_handler_bigip2]: CREATE_FAILED  BadRequest: resources.bigip_nnic_handler_bigip2.resources.network_vlan_ports.resources.network_vlan_ports.resources[2].resources.bigip_neutron_port: Invalid input for fixed_ips. Reason: 'f5-ha-internal' is not a valid UUID.
Neutron server returns request_
2018-06-24 20:56:04Z [activeactive]: CREATE_FAILED  Resource CREATE failed: BadRequest: resources.bigip_nnic_handler_bigip2.resources.network_vlan_ports.resources.network_vlan_ports.resources[2].resources.bigip_neutron_port: Invalid input for fixed_ips. Reason: 'f5-ha-internal' is not a valid UUID.

**Comment by vishwanathj** [comment]
Seems like the command you asked me to execute works fine

tosca@toscapkg003:~/f5-openstack-hot/experimental/templates/cluster/nnic/prod_stack/static$ openstack port create test_f5_bug_port --network f5-vip --fixed-ip subnet=f5-vip-ext
+-----------------------+-------------------------------------------------------------------------------+
| Field                 | Value                                                                         |
+-----------------------+-------------------------------------------------------------------------------+
| admin_state_up        | UP                                                                            |
| allowed_address_pairs |                                                                               |
| binding_host_id       | None                                                                          |
| binding_profile       | None                                                                          |
| binding_vif_details   | None                                                                          |
| binding_vif_type      | None                                                                          |
| binding_vnic_type     | normal                                                                        |
| created_at            | 2018-06-25T18:50:35Z                                                          |
| data_plane_status     | None                                                                          |
| description           |                                                                               |
| device_id             |                                                                               |
| device_owner          |                                                                               |
| dns_assignment        | None                                                                          |
| dns_domain            | None                                                                          |
| dns_name              | None                                                                          |
| extra_dhcp_opts       |                                                                               |
| fixed_ips             | ip_address='169.62.157.187', subnet_id='72999ed2-60dd-4542-82b9-c6726966fb76' |
| id                    | 8a996d49-b081-495d-be97-b6b08b7bf97e                                          |
| ip_address            | None                                                                          |
| mac_address           | fa:16:3e:4a:ad:9e                                                             |
| name                  | test_f5_bug_port                                                              |
| network_id            | e00f5ec3-2542-4b9a-a054-5aabe38a6000                                          |
| option_name           | None                                                                          |
| option_value          | None                                                                          |
| port_security_enabled | True                                                                          |
| project_id            | c6909a2f64854c44bd8f978a09753bc0                                              |
| qos_policy_id         | None                                                                          |
| revision_number       | 5                                                                             |
| security_group_ids    | 7badbd28-d61f-476e-8daa-d9739f2bf2dd                                          |
| status                | DOWN                                                                          |
| subnet_id             | None                                                                          |
| tags                  |                                                                               |
| trunk_details         | None                                                                          |
| updated_at            | 2018-06-25T18:50:35Z                                                          |
+-----------------------+-------------------------------------------------------------------------------+

**Comment by kaustriaf5** [comment]
@vishwanathj Did you try with the `f5-ha-internal`?

**Comment by vishwanathj** [comment]
I re-ran stack again with environment file having the network and subnet names and below is the output (Note: At the bottom I have the output for a successful port creation using network name and subnet name )

2018-06-25 19:18:56Z [standalone.security_groups]: CREATE_COMPLETE  state changed
2018-06-25 19:18:56Z [standalone.init_3_onboard_scripts]: CREATE_COMPLETE  state changed
2018-06-25 19:18:56Z [standalone.bigip_nnic_handler]: CREATE_IN_PROGRESS  state changed
2018-06-25 19:19:05Z [standalone.bigip_nnic_handler]: CREATE_FAILED  BadRequest: resources.bigip_nnic_handler.resources.network_vlan_ports.resources.network_vlan_ports.resources[1].resources.bigip_neutron_port: Invalid input for fixed_ips. Reason: 'f5-internal-subnet' is not a valid UUID.
Neutron server returns request_ids
2018-06-25 19:19:05Z [standalone]: CREATE_FAILED  Resource CREATE failed: BadRequest: resources.bigip_nnic_handler.resources.network_vlan_ports.resources.network_vlan_ports.resources[1].resources.bigip_neutron_port: Invalid input for fixed_ips. Reason: 'f5-internal-subnet' is not a valid UUID.


tosca@toscapkg003:~/f5-openstack-hot/experimental/templates/cluster/nnic/prod_stack/static$ openstack port create test_f5_bug_port --network f5-internal --fixed-ip subnet=f5-internal-subnet
+-----------------------+-----------------------------------------------------------------------------+
| Field                 | Value                                                                       |
+-----------------------+-----------------------------------------------------------------------------+
| admin_state_up        | UP                                                                          |
| allowed_address_pairs |                                                                             |
| binding_host_id       | None                                                                        |
| binding_profile       | None                                                                        |
| binding_vif_details   | None                                                                        |
| binding_vif_type      | None                                                                        |
| binding_vnic_type     | normal                                                                      |
| created_at            | 2018-06-25T19:11:35Z                                                        |
| data_plane_status     | None                                                                        |
| description           |                                                                             |
| device_id             |                                                                             |
| device_owner          |                                                                             |
| dns_assignment        | None                                                                        |
| dns_domain            | None                                                                        |
| dns_name              | None                                                                        |
| extra_dhcp_opts       |                                                                             |
| fixed_ips             | ip_address='10.187.98.20', subnet_id='9a2352b3-cecf-456e-aef8-00555d82de8b' |
| id                    | 74a56715-d933-40e9-9b92-d175e105e0ce                                        |
| ip_address            | None                                                                        |
| mac_address           | fa:16:3e:26:b1:19                                                           |
| name                  | test_f5_bug_port                                                            |
| network_id            | 4a80c5a3-e826-456d-b908-113cd5167cd0                                        |
| option_name           | None                                                                        |
| option_value          | None                                                                        |
| port_security_enabled | True                                                                        |
| project_id            | c6909a2f64854c44bd8f978a09753bc0                                            |
| qos_policy_id         | None                                                                        |
| revision_number       | 5                                                                           |
| security_group_ids    | 7badbd28-d61f-476e-8daa-d9739f2bf2dd                                        |
| status                | DOWN                                                                        |
| subnet_id             | None                                                                        |
| tags                  |                                                                             |
| trunk_details         | None                                                                        |
| updated_at            | 2018-06-25T19:11:35Z                                                        |
+-----------------------+-----------------------------------------------------------------------------+

**Comment by kaustriaf5** [comment]
@vishwanathj can you please provide the output of `openstack subnet show f5-internal-subnet`?

**Comment by vishwanathj** [comment]
@kaustriaf5 find below the output of the above command that you requested

openstack subnet show f5-internal-subnet
+-------------------+--------------------------------------+
| Field             | Value                                |
+-------------------+--------------------------------------+
| allocation_pools  | 10.187.98.18-10.187.98.30            |
| cidr              | 10.187.98.16/28                      |
| created_at        | 2018-06-09T20:20:35Z                 |
| description       |                                      |
| dns_nameservers   |                                      |
| enable_dhcp       | False                                |
| gateway_ip        | 10.187.98.17                         |
| host_routes       |                                      |
| id                | 9a2352b3-cecf-456e-aef8-00555d82de8b |
| ip_version        | 4                                    |
| ipv6_address_mode | None                                 |
| ipv6_ra_mode      | None                                 |
| name              | f5-internal-subnet                   |
| network_id        | 4a80c5a3-e826-456d-b908-113cd5167cd0 |
| project_id        | c6909a2f64854c44bd8f978a09753bc0     |
| revision_number   | 4                                    |
| segment_id        | None                                 |
| service_types     |                                      |
| subnetpool_id     | None                                 |
| tags              |                                      |
| updated_at        | 2018-06-22T22:24:45Z                 |

**Comment by kaustriaf5** [comment]
@vishwanathj This was determined to be dependent on the version of your OpenStack deployment.
Mitaka supports this, but later versions like Ocata requires the UUID for some reason. To change this you will need to file an issue directly to the OpenStack upstream repo / your OpenStack vendor. 
Closing this issue.
