### ISSUE TITLE
We should support a set of templates which don't force the creation of a floating IP on all management ports

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-hot#5]
There are many clouds with dedicated OAM provider networks which can be accessed by orchestration without the use of a floating IP. For such networks, using up a Floating IP for each management network is going to run the tenant project out of quotta for Floating IPs very quickly.

**Comment by kaustriaf5** [comment]
Fixed in this release:
https://github.com/F5Networks/f5-openstack-hot/releases/tag/v4.0.0

@jgruber 
Templates are under `prod_stack` directory
