### ISSUE TITLE
The network (data) ports need to be exposed in the output of the templates

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-hot#6]
The network ports need to exposed via the output of the templates. If the port is exposed, appropriate fixed_ips can be added and floating IP addresses can be associated with virtual addresses.

**Comment by kaustriaf5** [comment]
The network port_ids are already listed as output parameters for the following:
standalone_2_nic
standalone_n_nic
Need to add to the following:
cluster_2_nic
autoscale_ltm_2_nic
