### ISSUE TITLE
onboard.sh BIG-IP hostname generation problems

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-hot#7]
The templates pass in bigip_device_name(s) using the port 'dns_assignment' attribute. That assume that the port has had a Designate managed fqdn associated with it. That's rarely the case. 

When there is no dns_assignment attribute, the onboard.sh script tries to generate an hostname based on the IP address of the management port. This is fine as long as the IP address assigned to the management IP (IPv4 or IPv6) is manipulated to fit RFC 1126 compliant hostnames. It also assumes the domain part of the FQDN can be derived from the /etc/resolv.conf file search entry, which assumes there is only one search entry, and that there is one.

There should be a more deterministic way of populating the hostName if no 'dns_assignment' is found on the port. The port UUID is always an option which will always be present. It is 36 characters long (UUID4 with dashes). We just have to make sure that total fqdn does not exceed 255 characters.

**Comment by jkarlssonf5** [comment]
This also breaks cluster creation since onboard.sh and onboard-cluster.sh generates hostnames in two different ways. Once onboard.sh is complete the hostname will be (for example), “host-192.168.0.5.openstacklocal” while onboard-cluster.sh will come up with something like “cl-antiuon-0-tkfxwrpgm7tq-bigip-instance-5r7ahz3x6cou.novalocal” and does not modify bigip_base.conf to reflect this.

**Comment by kaustriaf5** [comment]
Thanks for reporting, we have a fix due for release tomorrow that will ensure the hostname is sync'd up.

**Comment by kaustriaf5** [comment]
@jkarlssonf5 when you get a chance, please grab latest (v3.0.0) and let me know if you are still having issues. Thanks!

**Comment by kaustriaf5** [comment]
@jgruber - what do we want to do if there is no dns /etc/resolv.conf file search entry?
Assign default domain name (i.e. openstacklocal) so that  modifying `sys global settings` succeeds (since it requires FQDN) ?

**Comment by jkarlssonf5** [comment]
@kaustriaf5 - Sorry for not responding faster. Started testing yesterday and something is still broken, at least in my environment. Will try to figure out what it is ASAP.
